---
- name: Imprimir Loops
  hosts: localhost
  vars_files: 
    - vars/list_color.yml
  tasks: 
    - name: Print
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ colores }}"
