---
- name: Imprimir Loops
  hosts: localhost
  vars_files: 
    - vars/list_color.yml

  vars:
    color:
      - negro
      - verde
      - gris
  tasks: 
    - name: Print
      ansible.builtin.debug:
        msg: "{{ color }}"
