---
- name: Imprimir Loops
  hosts: localhost
  vars_files: 
    - vars/list_color.yml

  vars: 
    - color: 
        - gray
        - black
        - white
    
  tasks: 
    - name: Print
      ansible.builtin.shell: "echo {{ item }}"
      loop: "{{ lookup('ansible.builtin.vars', 'colores', wantlist=true) | default(color)  }}"


