---
- name: Imprimir Loops
  hosts: localhost
  vars:
    - list_colores_survey: "{{ colores_survey | split(',') }}"
    
  tasks: 
    - name: Print colores_survey
      ansible.builtin.shell: "echo {{ item }}"
      loop: "{{ list_colores_survey | list }}"
